extends Resource
class_name Peliculas

# nombre
# anio_estreno
# presupuesto (en millones de USD)
# clasificacion
# calificacion (rating IMDB escalado 1-100)
# estudio
# director
# protagonistas (verde si está en la lista, amarillo si es secundario)
# secundarios (verde si está en la lista, amarillo si es protagonista)
# generos (verde por cada uno que coincida)

enum Clasificacion { ATP, MAS_13, MAS_18 }

enum GeneroCine {
	ACCION,
	COMEDIA,
	CRIMEN,
	DRAMA,
	TERROR,
	ROMANCE,
	SCI_FI,
	ANIMACION,
	THRILLER,
	FANTASIA,
	DOCUMENTAL,
	HISTORIA,
	AVENTURA,
	MUSICA,
	MISTERIO,
	WESTERN,
	BELICO
}

const LISTA_PELICULAS = [
	{
		"nombre": "Volver al Futuro",
		"anio_estreno": 1985,
		"presupuesto": 19,
		"clasificacion": Clasificacion.ATP,
		"calificacion": 86,
		"estudio": "Universal",
		"director": "Robert Zemeckis",
		"protagonistas": ["Michael J. Fox"],
		"secundarios": ["Christopher Lloyd", "Lea Thompson", "Crispin Glover"],
		"generos": [GeneroCine.SCI_FI, GeneroCine.AVENTURA, GeneroCine.COMEDIA]
	},
	{
		"nombre": "Avengers: Endgame",
		"anio_estreno": 2019,
		"presupuesto": 356,
		"clasificacion": Clasificacion.MAS_13,
		"calificacion": 84,
		"estudio": "Marvel Studios",
		"director": "Anthony y Joe Russo",
		"protagonistas": ["Robert Downey Jr.", "Chris Evans"],
		"secundarios": ["Scarlett Johansson", "Chris Hemsworth", "Mark Ruffalo", "Jeremy Renner"],
		"generos": [GeneroCine.ACCION, GeneroCine.AVENTURA, GeneroCine.SCI_FI]
	},
	{
		"nombre": "Toy Story",
		"anio_estreno": 1995,
		"presupuesto": 30,
		"clasificacion": Clasificacion.ATP,
		"calificacion": 83,
		"estudio": "Pixar",
		"director": "John Lasseter",
		"protagonistas": ["Tom Hanks"],
		"secundarios": ["Tim Allen", "Don Rickles"],
		"generos": [GeneroCine.ANIMACION, GeneroCine.AVENTURA, GeneroCine.COMEDIA]
	},
	{
		"nombre": "El Rey León",
		"anio_estreno": 1994,
		"presupuesto": 45,
		"clasificacion": Clasificacion.ATP,
		"calificacion": 85,
		"estudio": "Disney",
		"director": "Roger Allers y Rob Minkoff",
		"protagonistas": ["Matthew Broderick"],
		"secundarios": ["Jeremy Irons", "James Earl Jones", "Nathan Lane"],
		"generos": [GeneroCine.ANIMACION, GeneroCine.DRAMA, GeneroCine.AVENTURA]
	},
	{
		"nombre": "El Padrino",
		"anio_estreno": 1972,
		"presupuesto": 6,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 92,
		"estudio": "Paramount",
		"director": "Francis Ford Coppola",
		"protagonistas": ["Marlon Brando"],
		"secundarios": ["Al Pacino", "James Caan", "Robert Duvall", "Diane Keaton"],
		"generos": [GeneroCine.DRAMA, GeneroCine.CRIMEN]
	},
	{
		"nombre": "Titanic",
		"anio_estreno": 1997,
		"presupuesto": 200,
		"clasificacion": Clasificacion.MAS_13,
		"calificacion": 79,
		"estudio": "Paramount",
		"director": "James Cameron",
		"protagonistas": ["Leonardo DiCaprio", "Kate Winslet"],
		"secundarios": ["Billy Zane", "Kathy Bates"],
		"generos": [GeneroCine.DRAMA, GeneroCine.ROMANCE]
	},
	{
		"nombre": "Inception",
		"anio_estreno": 2010,
		"presupuesto": 160,
		"clasificacion": Clasificacion.MAS_13,
		"calificacion": 87,
		"estudio": "Warner Bros",
		"director": "Christopher Nolan",
		"protagonistas": ["Leonardo DiCaprio"],
		"secundarios": ["Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy", "Ken Watanabe"],
		"generos": [GeneroCine.ACCION, GeneroCine.SCI_FI, GeneroCine.THRILLER]
	},
	{
		"nombre": "Joker",
		"anio_estreno": 2019,
		"presupuesto": 55,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 82,
		"estudio": "Warner Bros",
		"director": "Todd Phillips",
		"protagonistas": ["Joaquin Phoenix"],
		"secundarios": ["Robert De Niro", "Zazie Beetz", "Frances Conroy"],
		"generos": [GeneroCine.DRAMA, GeneroCine.THRILLER]
	},
	{
		"nombre": "Interstellar",
		"anio_estreno": 2014,
		"presupuesto": 165,
		"clasificacion": Clasificacion.ATP,
		"calificacion": 86,
		"estudio": "Warner Bros",
		"director": "Christopher Nolan",
		"protagonistas": ["Matthew McConaughey"],
		"secundarios": ["Anne Hathaway", "Jessica Chastain", "Michael Caine"],
		"generos": [GeneroCine.SCI_FI, GeneroCine.DRAMA, GeneroCine.AVENTURA]
	},
	{
		"nombre": "Pulp Fiction",
		"anio_estreno": 1994,
		"presupuesto": 8,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 89,
		"estudio": "Miramax",
		"director": "Quentin Tarantino",
		"protagonistas": ["John Travolta", "Samuel L. Jackson"],
		"secundarios": ["Uma Thurman", "Bruce Willis", "Harvey Keitel"],
		"generos": [GeneroCine.THRILLER, GeneroCine.CRIMEN, GeneroCine.COMEDIA]
	},
	{
		"nombre": "Coco",
		"anio_estreno": 2017,
		"presupuesto": 175,
		"clasificacion": Clasificacion.ATP,
		"calificacion": 84,
		"estudio": "Pixar",
		"director": "Lee Unkrich",
		"protagonistas": ["Anthony Gonzalez"],
		"secundarios": ["Gael García Bernal", "Benjamin Bratt", "Alanna Ubach"],
		"generos": [GeneroCine.ANIMACION, GeneroCine.AVENTURA, GeneroCine.MUSICA]
	},
	{
		"nombre": "Gladiador",
		"anio_estreno": 2000,
		"presupuesto": 103,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 86,
		"estudio": "Universal",
		"director": "Ridley Scott",
		"protagonistas": ["Russell Crowe"],
		"secundarios": ["Joaquin Phoenix", "Connie Nielsen", "Oliver Reed"],
		"generos": [GeneroCine.ACCION, GeneroCine.DRAMA, GeneroCine.AVENTURA]
	},
	{
		"nombre": "Get Out",
		"anio_estreno": 2017,
		"presupuesto": 5,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 78,
		"estudio": "Universal",
		"director": "Jordan Peele",
		"protagonistas": ["Daniel Kaluuya"],
		"secundarios": ["Allison Williams", "Bradley Whitford", "Catherine Keener"],
		"generos": [GeneroCine.TERROR, GeneroCine.THRILLER]
	},
	{
		"nombre": "El Señor de los Anillos: La Comunidad del Anillo",
		"anio_estreno": 2001,
		"presupuesto": 93,
		"clasificacion": Clasificacion.MAS_13,
		"calificacion": 91,
		"estudio": "New Line Cinema",
		"director": "Peter Jackson",
		"protagonistas": ["Elijah Wood"],
		"secundarios": ["Ian McKellen", "Viggo Mortensen", "Orlando Bloom", "Sean Bean"],
		"generos": [GeneroCine.FANTASIA, GeneroCine.AVENTURA, GeneroCine.DRAMA]
	},
	{
		"nombre": "Forrest Gump",
		"anio_estreno": 1994,
		"presupuesto": 55,
		"clasificacion": Clasificacion.MAS_13,
		"calificacion": 88,
		"estudio": "Paramount",
		"director": "Robert Zemeckis",
		"protagonistas": ["Tom Hanks"],
		"secundarios": ["Robin Wright", "Gary Sinise", "Sally Field"],
		"generos": [GeneroCine.DRAMA, GeneroCine.ROMANCE, GeneroCine.COMEDIA]
	},
	{
		"nombre": "Matrix",
		"anio_estreno": 1999,
		"presupuesto": 63,
		"clasificacion": Clasificacion.MAS_13,
		"calificacion": 83,
		"estudio": "Warner Bros",
		"director": "Lana y Lilly Wachowski",
		"protagonistas": ["Keanu Reeves"],
		"secundarios": ["Laurence Fishburne", "Carrie-Anne Moss", "Hugo Weaving"],
		"generos": [GeneroCine.SCI_FI, GeneroCine.ACCION, GeneroCine.THRILLER]
	},
	{
		"nombre": "Parasite",
		"anio_estreno": 2019,
		"presupuesto": 11,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 86,
		"estudio": "CJ Entertainment",
		"director": "Bong Joon-ho",
		"protagonistas": ["Song Kang-ho"],
		"secundarios": ["Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik"],
		"generos": [GeneroCine.THRILLER, GeneroCine.DRAMA]
	},
	{
		"nombre": "Shrek",
		"anio_estreno": 2001,
		"presupuesto": 60,
		"clasificacion": Clasificacion.ATP,
		"calificacion": 78,
		"estudio": "DreamWorks",
		"director": "Andrew Adamson y Vicky Jenson",
		"protagonistas": ["Mike Myers"],
		"secundarios": ["Eddie Murphy", "Cameron Diaz", "John Lithgow"],
		"generos": [GeneroCine.ANIMACION, GeneroCine.COMEDIA, GeneroCine.FANTASIA]
	},
	{
		"nombre": "Whiplash",
		"anio_estreno": 2014,
		"presupuesto": 3,
		"clasificacion": Clasificacion.MAS_13,
		"calificacion": 87,
		"estudio": "Sony Pictures",
		"director": "Damien Chazelle",
		"protagonistas": ["Miles Teller"],
		"secundarios": ["J.K. Simmons", "Paul Reiser", "Melissa Benoist"],
		"generos": [GeneroCine.DRAMA, GeneroCine.MUSICA]
	},
	{
		"nombre": "Alien",
		"anio_estreno": 1979,
		"presupuesto": 11,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 85,
		"estudio": "20th Century Fox",
		"director": "Ridley Scott",
		"protagonistas": ["Sigourney Weaver"],
		"secundarios": ["Tom Skerritt", "John Hurt", "Ian Holm"],
		"generos": [GeneroCine.TERROR, GeneroCine.SCI_FI, GeneroCine.THRILLER]
	},
	{
		"nombre": "Ratatouille",
		"anio_estreno": 2007,
		"presupuesto": 150,
		"clasificacion": Clasificacion.ATP,
		"calificacion": 80,
		"estudio": "Pixar",
		"director": "Brad Bird",
		"protagonistas": ["Patton Oswalt"],
		"secundarios": ["Lou Romano", "Ian Holm", "Peter O'Toole"],
		"generos": [GeneroCine.ANIMACION, GeneroCine.COMEDIA]
	},
	{
		"nombre": "Mad Max: Fury Road",
		"anio_estreno": 2015,
		"presupuesto": 185,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 81,
		"estudio": "Warner Bros",
		"director": "George Miller",
		"protagonistas": ["Tom Hardy", "Charlize Theron"],
		"secundarios": ["Nicholas Hoult", "Hugh Keays-Byrne"],
		"generos": [GeneroCine.ACCION, GeneroCine.AVENTURA, GeneroCine.SCI_FI]
	},
	{
		"nombre": "Brokeback Mountain",
		"anio_estreno": 2005,
		"presupuesto": 14,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 79,
		"estudio": "Focus Features",
		"director": "Ang Lee",
		"protagonistas": ["Heath Ledger", "Jake Gyllenhaal"],
		"secundarios": ["Michelle Williams", "Anne Hathaway"],
		"generos": [GeneroCine.DRAMA, GeneroCine.ROMANCE]
	},
	{
		"nombre": "Spider-Man: Into the Spider-Verse",
		"anio_estreno": 2018,
		"presupuesto": 90,
		"clasificacion": Clasificacion.ATP,
		"calificacion": 84,
		"estudio": "Sony Pictures",
		"director": "Bob Persichetti y Peter Ramsey",
		"protagonistas": ["Shameik Moore"],
		"secundarios": ["Jake Johnson", "Hailee Steinfeld", "Mahershala Ali"],
		"generos": [GeneroCine.ANIMACION, GeneroCine.ACCION, GeneroCine.AVENTURA]
	},
	{
		"nombre": "The Dark Knight",
		"anio_estreno": 2008,
		"presupuesto": 185,
		"clasificacion": Clasificacion.MAS_13,
		"calificacion": 90,
		"estudio": "Warner Bros",
		"director": "Christopher Nolan",
		"protagonistas": ["Christian Bale"],
		"secundarios": ["Heath Ledger", "Aaron Eckhart", "Michael Caine", "Maggie Gyllenhaal"],
		"generos": [GeneroCine.ACCION, GeneroCine.THRILLER, GeneroCine.DRAMA]
	},
	{
		"nombre": "Jurassic Park",
		"anio_estreno": 1993,
		"presupuesto": 63,
		"clasificacion": Clasificacion.MAS_13,
		"calificacion": 82,
		"estudio": "Universal",
		"director": "Steven Spielberg",
		"protagonistas": ["Sam Neill"],
		"secundarios": ["Jeff Goldblum", "Laura Dern", "Richard Attenborough"],
		"generos": [GeneroCine.SCI_FI, GeneroCine.AVENTURA, GeneroCine.THRILLER]
	},
	{
		"nombre": "Up",
		"anio_estreno": 2009,
		"presupuesto": 175,
		"clasificacion": Clasificacion.ATP,
		"calificacion": 82,
		"estudio": "Pixar",
		"director": "Pete Docter",
		"protagonistas": ["Edward Asner"],
		"secundarios": ["Jordan Nagai", "Christopher Plummer", "John Ratzenberger"],
		"generos": [GeneroCine.ANIMACION, GeneroCine.AVENTURA, GeneroCine.COMEDIA]
	},
	{
		"nombre": "Scarface",
		"anio_estreno": 1983,
		"presupuesto": 35,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 82,
		"estudio": "Universal",
		"director": "Brian De Palma",
		"protagonistas": ["Al Pacino"],
		"secundarios": ["Michelle Pfeiffer", "Steven Bauer", "Mary Elizabeth Mastrantonio"],
		"generos": [GeneroCine.DRAMA, GeneroCine.CRIMEN, GeneroCine.ACCION]
	},
	{
		"nombre": "La La Land",
		"anio_estreno": 2016,
		"presupuesto": 30,
		"clasificacion": Clasificacion.ATP,
		"calificacion": 81,
		"estudio": "Lionsgate",
		"director": "Damien Chazelle",
		"protagonistas": ["Ryan Gosling", "Emma Stone"],
		"secundarios": ["John Legend", "Rosemarie DeWitt"],
		"generos": [GeneroCine.MUSICA, GeneroCine.ROMANCE, GeneroCine.DRAMA]
	},
	{
		"nombre": "Amélie",
		"anio_estreno": 2001,
		"presupuesto": 10,
		"clasificacion": Clasificacion.MAS_13,
		"calificacion": 80,
		"estudio": "UGC",
		"director": "Jean-Pierre Jeunet",
		"protagonistas": ["Audrey Tautou"],
		"secundarios": ["Mathieu Kassovitz", "Rufus", "Yolande Moreau"],
		"generos": [GeneroCine.ROMANCE, GeneroCine.COMEDIA, GeneroCine.DRAMA]
	},
	{
		"nombre": "Schindler's List",
		"anio_estreno": 1993,
		"presupuesto": 22,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 90,
		"estudio": "Universal",
		"director": "Steven Spielberg",
		"protagonistas": ["Liam Neeson"],
		"secundarios": ["Ralph Fiennes", "Ben Kingsley", "Embeth Davidtz"],
		"generos": [GeneroCine.DRAMA, GeneroCine.BELICO, GeneroCine.HISTORIA]
	},
	{
		"nombre": "Eternal Sunshine of the Spotless Mind",
		"anio_estreno": 2004,
		"presupuesto": 20,
		"clasificacion": Clasificacion.MAS_13,
		"calificacion": 83,
		"estudio": "Focus Features",
		"director": "Michel Gondry",
		"protagonistas": ["Jim Carrey", "Kate Winslet"],
		"secundarios": ["Kirsten Dunst", "Mark Ruffalo", "Elijah Wood"],
		"generos": [GeneroCine.DRAMA, GeneroCine.ROMANCE, GeneroCine.SCI_FI]
	},
	{
		"nombre": "Goodfellas",
		"anio_estreno": 1990,
		"presupuesto": 25,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 88,
		"estudio": "Warner Bros",
		"director": "Martin Scorsese",
		"protagonistas": ["Ray Liotta"],
		"secundarios": ["Robert De Niro", "Joe Pesci", "Lorraine Bracco"],
		"generos": [GeneroCine.DRAMA, GeneroCine.THRILLER, GeneroCine.CRIMEN]
	},
	{
		"nombre": "2001: A Space Odyssey",
		"anio_estreno": 1968,
		"presupuesto": 12,
		"clasificacion": Clasificacion.ATP,
		"calificacion": 83,
		"estudio": "Warner Bros",
		"director": "Stanley Kubrick",
		"protagonistas": ["Keir Dullea"],
		"secundarios": ["Gary Lockwood", "William Sylvester"],
		"generos": [GeneroCine.SCI_FI, GeneroCine.DRAMA]
	},
	{
		"nombre": "Django Unchained",
		"anio_estreno": 2012,
		"presupuesto": 100,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 86,
		"estudio": "Sony Pictures",
		"director": "Quentin Tarantino",
		"protagonistas": ["Jamie Foxx"],
		"secundarios": ["Christoph Waltz", "Leonardo DiCaprio", "Kerry Washington", "Samuel L. Jackson"],
		"generos": [GeneroCine.WESTERN, GeneroCine.DRAMA, GeneroCine.ACCION]
	},
	{
		"nombre": "Her",
		"anio_estreno": 2013,
		"presupuesto": 23,
		"clasificacion": Clasificacion.MAS_13,
		"calificacion": 80,
		"estudio": "Warner Bros",
		"director": "Spike Jonze",
		"protagonistas": ["Joaquin Phoenix"],
		"secundarios": ["Amy Adams", "Rooney Mara", "Olivia Wilde"],
		"generos": [GeneroCine.DRAMA, GeneroCine.ROMANCE, GeneroCine.SCI_FI]
	},
	{
		"nombre": "Moonlight",
		"anio_estreno": 2016,
		"presupuesto": 4,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 79,
		"estudio": "A24",
		"director": "Barry Jenkins",
		"protagonistas": ["Trevante Rhodes"],
		"secundarios": ["Mahershala Ali", "Naomie Harris", "Janelle Monáe"],
		"generos": [GeneroCine.DRAMA]
	},
	{
		"nombre": "Blade Runner 2049",
		"anio_estreno": 2017,
		"presupuesto": 150,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 80,
		"estudio": "Warner Bros",
		"director": "Denis Villeneuve",
		"protagonistas": ["Ryan Gosling"],
		"secundarios": ["Harrison Ford", "Ana de Armas", "Jared Leto"],
		"generos": [GeneroCine.SCI_FI, GeneroCine.THRILLER, GeneroCine.DRAMA]
	},
	{
		"nombre": "Everything Everywhere All at Once",
		"anio_estreno": 2022,
		"presupuesto": 14,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 79,
		"estudio": "A24",
		"director": "Daniel Kwan y Daniel Scheinert",
		"protagonistas": ["Michelle Yeoh"],
		"secundarios": ["Ke Huy Quan", "Jamie Lee Curtis", "Stephanie Hsu"],
		"generos": [GeneroCine.ACCION, GeneroCine.COMEDIA, GeneroCine.SCI_FI]
	},
	{
		"nombre": "Dune",
		"anio_estreno": 2021,
		"presupuesto": 165,
		"clasificacion": Clasificacion.MAS_13,
		"calificacion": 79,
		"estudio": "Warner Bros",
		"director": "Denis Villeneuve",
		"protagonistas": ["Timothée Chalamet"],
		"secundarios": ["Zendaya", "Rebecca Ferguson", "Oscar Isaac", "Josh Brolin"],
		"generos": [GeneroCine.SCI_FI, GeneroCine.AVENTURA, GeneroCine.DRAMA]
	},
	{
		"nombre": "Midsommar",
		"anio_estreno": 2019,
		"presupuesto": 9,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 74,
		"estudio": "A24",
		"director": "Ari Aster",
		"protagonistas": ["Florence Pugh"],
		"secundarios": ["Jack Reynor", "William Jackson Harper", "Vilhelm Blomgren"],
		"generos": [GeneroCine.TERROR, GeneroCine.DRAMA, GeneroCine.MISTERIO]
	},
	{
		"nombre": "Oppenheimer",
		"anio_estreno": 2023,
		"presupuesto": 100,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 88,
		"estudio": "Universal",
		"director": "Christopher Nolan",
		"protagonistas": ["Cillian Murphy"],
		"secundarios": ["Emily Blunt", "Robert Downey Jr.", "Matt Damon", "Florence Pugh"],
		"generos": [GeneroCine.DRAMA, GeneroCine.BELICO, GeneroCine.THRILLER]
	},
	{
		"nombre": "Barbie",
		"anio_estreno": 2023,
		"presupuesto": 145,
		"clasificacion": Clasificacion.MAS_13,
		"calificacion": 70,
		"estudio": "Warner Bros",
		"director": "Greta Gerwig",
		"protagonistas": ["Margot Robbie", "Ryan Gosling"],
		"secundarios": ["America Ferrera", "Kate McKinnon", "Issa Rae", "Simu Liu"],
		"generos": [GeneroCine.COMEDIA, GeneroCine.AVENTURA]
	},
	{
		"nombre": "The Shawshank Redemption",
		"anio_estreno": 1994,
		"presupuesto": 25,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 93,
		"estudio": "Castle Rock Entertainment",
		"director": "Frank Darabont",
		"protagonistas": ["Tim Robbins"],
		"secundarios": ["Morgan Freeman", "Bob Gunton", "William Sadler"],
		"generos": [GeneroCine.DRAMA, GeneroCine.CRIMEN]
	},
	{
		"nombre": "Spirited Away",
		"anio_estreno": 2001,
		"presupuesto": 19,
		"clasificacion": Clasificacion.ATP,
		"calificacion": 85,
		"estudio": "Studio Ghibli",
		"director": "Hayao Miyazaki",
		"protagonistas": ["Daveigh Chase"],
		"secundarios": ["Suzanne Pleshette", "Miyu Irino", "Jason Marsden"],
		"generos": [GeneroCine.ANIMACION, GeneroCine.FANTASIA, GeneroCine.AVENTURA]
	},
	{
		"nombre": "Silence of the Lambs",
		"anio_estreno": 1991,
		"presupuesto": 19,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 88,
		"estudio": "Orion Pictures",
		"director": "Jonathan Demme",
		"protagonistas": ["Jodie Foster"],
		"secundarios": ["Anthony Hopkins", "Scott Glenn", "Ted Levine"],
		"generos": [GeneroCine.THRILLER, GeneroCine.TERROR, GeneroCine.MISTERIO]
	},
	{
		"nombre": "Fight Club",
		"anio_estreno": 1999,
		"presupuesto": 63,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 88,
		"estudio": "20th Century Fox",
		"director": "David Fincher",
		"protagonistas": ["Brad Pitt", "Edward Norton"],
		"secundarios": ["Helena Bonham Carter", "Meat Loaf"],
		"generos": [GeneroCine.DRAMA, GeneroCine.THRILLER]
	},
	{
		"nombre": "Leon: The Professional",
		"anio_estreno": 1994,
		"presupuesto": 16,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 84,
		"estudio": "Gaumont",
		"director": "Luc Besson",
		"protagonistas": ["Jean Reno"],
		"secundarios": ["Natalie Portman", "Gary Oldman", "Danny Aiello"],
		"generos": [GeneroCine.ACCION, GeneroCine.CRIMEN, GeneroCine.DRAMA]
	},
	{
		"nombre": "Saving Private Ryan",
		"anio_estreno": 1998,
		"presupuesto": 70,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 88,
		"estudio": "DreamWorks",
		"director": "Steven Spielberg",
		"protagonistas": ["Tom Hanks"],
		"secundarios": ["Matt Damon", "Tom Sizemore", "Edward Burns", "Barry Pepper"],
		"generos": [GeneroCine.BELICO, GeneroCine.DRAMA, GeneroCine.ACCION]
	},
	{
		"nombre": "Requiem for a Dream",
		"anio_estreno": 2000,
		"presupuesto": 4,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 79,
		"estudio": "Artisan Entertainment",
		"director": "Darren Aronofsky",
		"protagonistas": ["Ellen Burstyn"],
		"secundarios": ["Jared Leto", "Jennifer Connelly", "Marlon Wayans"],
		"generos": [GeneroCine.DRAMA, GeneroCine.THRILLER]
	},
	{
		"nombre": "No Country for Old Men",
		"anio_estreno": 2007,
		"presupuesto": 25,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 88,
		"estudio": "Miramax",
		"director": "Joel y Ethan Coen",
		"protagonistas": ["Josh Brolin"],
		"secundarios": ["Javier Bardem", "Tommy Lee Jones", "Woody Harrelson"],
		"generos": [GeneroCine.THRILLER, GeneroCine.WESTERN, GeneroCine.DRAMA]
	},
	{
		"nombre": "WALL-E",
		"anio_estreno": 2008,
		"presupuesto": 180,
		"clasificacion": Clasificacion.ATP,
		"calificacion": 83,
		"estudio": "Pixar",
		"director": "Andrew Stanton",
		"protagonistas": ["Ben Burtt"],
		"secundarios": ["Elissa Knight", "Jeff Garlin", "Sigourney Weaver"],
		"generos": [GeneroCine.ANIMACION, GeneroCine.SCI_FI, GeneroCine.ROMANCE]
	},
	{
		"nombre": "Oldboy",
		"anio_estreno": 2003,
		"presupuesto": 3,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 82,
		"estudio": "Show East",
		"director": "Park Chan-wook",
		"protagonistas": ["Choi Min-sik"],
		"secundarios": ["Yoo Ji-tae", "Gang Hye-jung"],
		"generos": [GeneroCine.THRILLER, GeneroCine.MISTERIO, GeneroCine.DRAMA, GeneroCine.ACCION]
	},
	{
		"nombre": "Hereditary",
		"anio_estreno": 2018,
		"presupuesto": 10,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 74,
		"estudio": "A24",
		"director": "Ari Aster",
		"protagonistas": ["Toni Collette"],
		"secundarios": ["Gabriel Byrne", "Alex Wolff", "Milly Shapiro"],
		"generos": [GeneroCine.TERROR, GeneroCine.DRAMA]
	},
	{
		"nombre": "The Grand Budapest Hotel",
		"anio_estreno": 2014,
		"presupuesto": 25,
		"clasificacion": Clasificacion.MAS_13,
		"calificacion": 82,
		"estudio": "Fox Searchlight",
		"director": "Wes Anderson",
		"protagonistas": ["Ralph Fiennes"],
		"secundarios": ["Tony Revolori", "Saoirse Ronan", "Bill Murray", "Tilda Swinton"],
		"generos": [GeneroCine.COMEDIA, GeneroCine.DRAMA]
	},
	{
		"nombre": "Arrival",
		"anio_estreno": 2016,
		"presupuesto": 47,
		"clasificacion": Clasificacion.MAS_13,
		"calificacion": 79,
		"estudio": "Paramount",
		"director": "Denis Villeneuve",
		"protagonistas": ["Amy Adams"],
		"secundarios": ["Jeremy Renner", "Forest Whitaker", "Michael Stuhlbarg"],
		"generos": [GeneroCine.SCI_FI, GeneroCine.DRAMA, GeneroCine.MISTERIO]
	},
	{
		"nombre": "Casino",
		"anio_estreno": 1995,
		"presupuesto": 52,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 87,
		"estudio": "Universal",
		"director": "Martin Scorsese",
		"protagonistas": ["Robert De Niro"],
		"secundarios": ["Sharon Stone", "Joe Pesci", "James Woods"],
		"generos": [GeneroCine.DRAMA, GeneroCine.THRILLER, GeneroCine.CRIMEN]
	},
	{
		"nombre": "Pan's Labyrinth",
		"anio_estreno": 2006,
		"presupuesto": 19,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 81,
		"estudio": "Warner Bros",
		"director": "Guillermo del Toro",
		"protagonistas": ["Ivana Baquero"],
		"secundarios": ["Sergi López", "Maribel Verdú", "Doug Jones"],
		"generos": [GeneroCine.FANTASIA, GeneroCine.DRAMA, GeneroCine.BELICO]
	},
	{
		"nombre": "Nomadland",
		"anio_estreno": 2020,
		"presupuesto": 5,
		"clasificacion": Clasificacion.MAS_13,
		"calificacion": 74,
		"estudio": "Searchlight Pictures",
		"director": "Chloé Zhao",
		"protagonistas": ["Frances McDormand"],
		"secundarios": ["David Strathairn", "Linda May", "Swankie"],
		"generos": [GeneroCine.DRAMA]
	},
	{
		"nombre": "The Truman Show",
		"anio_estreno": 1998,
		"presupuesto": 60,
		"clasificacion": Clasificacion.ATP,
		"calificacion": 81,
		"estudio": "Paramount",
		"director": "Peter Weir",
		"protagonistas": ["Jim Carrey"],
		"secundarios": ["Laura Linney", "Ed Harris", "Noah Emmerich"],
		"generos": [GeneroCine.DRAMA, GeneroCine.COMEDIA]
	},
	{
		"nombre": "A Beautiful Mind",
		"anio_estreno": 2001,
		"presupuesto": 58,
		"clasificacion": Clasificacion.MAS_13,
		"calificacion": 78,
		"estudio": "Universal",
		"director": "Ron Howard",
		"protagonistas": ["Russell Crowe"],
		"secundarios": ["Jennifer Connelly", "Ed Harris", "Paul Bettany"],
		"generos": [GeneroCine.DRAMA, GeneroCine.ROMANCE]
	},
	{
		"nombre": "Crouching Tiger Hidden Dragon",
		"anio_estreno": 2000,
		"presupuesto": 17,
		"clasificacion": Clasificacion.MAS_13,
		"calificacion": 78,
		"estudio": "Sony Pictures",
		"director": "Ang Lee",
		"protagonistas": ["Chow Yun-fat", "Michelle Yeoh"],
		"secundarios": ["Zhang Ziyi", "Chang Chen"],
		"generos": [GeneroCine.ACCION, GeneroCine.DRAMA, GeneroCine.ROMANCE, GeneroCine.AVENTURA]
	},
	{
		"nombre": "Seven",
		"anio_estreno": 1995,
		"presupuesto": 33,
		"clasificacion": Clasificacion.MAS_18,
		"calificacion": 86,
		"estudio": "New Line Cinema",
		"director": "David Fincher",
		"protagonistas": ["Brad Pitt", "Morgan Freeman"],
		"secundarios": ["Kevin Spacey", "Gwyneth Paltrow", "R. Lee Ermey"],
		"generos": [GeneroCine.THRILLER, GeneroCine.MISTERIO, GeneroCine.DRAMA]
	},
]
